
global ROBOT_WHEEL_RADUIS ROBOT_DISTANCE_BETWEEN_WHEELS ROBOT_PROXIMITY_SENSORS_DIRECTIONS

% epuck's wheel radius
ROBOT_WHEEL_RADUIS=21; % mm 

% epuck's between wheels distance 
ROBOT_DISTANCE_BETWEEN_WHEELS=53; % mm

% epuck's proximity sensors positions 
%ROBOT_PROXIMITY_SENSORS_DIRECTIONS=[45, 30, 30, 30, 45, 60, 60, 60];
ROBOT_PROXIMITY_SENSORS_DIRECTIONS=[30, 45, 60, 60, 60, 45, 30, 30];